name: Container Image Scan

on:
  registry_package:

jobs:
  container-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Display Context
        uses: actions/github-script@v3
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));

      - name: Get Container Image from Commit Status
        id: container_image
        uses: actions/github-script@v2
        with:
          script: |
            const status = await github.repos.getCombinedStatusForRef({
                ...context.repo,
                ref: context.sha
            }).then(status => {
                if (status.data.statuses) {
                    return status.data.statuses.filter(status => {
                        return status.context === 'Container Image Published'
                    });
                }
                return null;
            });

            //TODO remove this
            console.log('----- Combined Statuses');
            console.log(JSON.stringify(status, null, 2));

            let containerStatus = null;
            if (!status) {
                // do nothing
            } else if (status.length === 1) {
              containerStatus = status[0];
            } else {
                // Assuming first the last is the latest, this should not happen in practice as this is for a single commit
                containerStatus = status[status.length - 1];
            }
            
            const containerParts = containerStatus.description.split(' ')
                , containerRegistry = containerParts[1]
                , containerImageTag = containerParts[0]
            ;
            core.setOutput('container_image_tag', containerImageTag);
            core.setOutput('container_registry', containerRegistry);
            console.log(`Container Image: ${containerImageTag}`);

      - name: GHPR Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker Pull Image
        env:
          IMAGE: ${{ steps.container_image.outputs.container_image_tag }}
          REGISTRY: ${{ steps.maven_build.outputs.container_registry }}
        run: |
          docker pull ${{ steps.container_image.outputs.container_image_tag }}

      - name: Scan Container Image
        uses: anchore/scan-action@v2
        with:
          image: ${{ steps.container_image.outputs.container_image_tag }}
          debug: true
          acs-report-enable: true

      - name: Display SARIF report data
        run: cat results.sarif

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
