name: Deploy Web App on Azure

on:
  deployment

jobs:
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest

    steps:
      - name: Extract Deployment Details and Report Deployment in Progress
        id: deployment_data
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const run = process.env.GITHUB_RUN_ID
              , log_url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${run}`
              ;

            //TODO remove
            console.log(JSON.stringify(context, null, 2));

            const deployment = context.payload.deployment
              , environment = deployment.environment
              , deploymentPayload = JSON.parse(deployment.payload)
              , containerRegistryUrl = `${deploymentPayload.container_registry}`
              , containerImage = `${deploymentPayload.container_image}`
              , deploymentRef = deploymentPayload.ref
              ;

            let webAppName = `${context.repo.repo}-${environment}`
            //if (environment !== 'prod') {
            //  webAppName += `-${deployment.id}`
            //}

            core.setOutput('container_registry_url', containerRegistryUrl);
            core.setOutput('container_image', containerImage);
            core.setOutput('webapp_name', webAppName);
            core.setOutput('deployment_github_ref', deploymentRef);
            core.setOutput('app_type', environment == 'prod' ? 'prod' : 'review');

            github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              mediaType: {
                previews: ["flash-preview", "ant-man"]
              },
              deployment_id: context.payload.deployment.id,
              state: 'in_progress',
              description: 'Deployment from GitHub Actions started',
              target_url: log_url,
              log_url: log_url
            })

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OCTODEMO_AZURE_CREDENTIALS }}

# TODO need to validate that the container image actually exists before we try to deploy the azure application!

      - name: Create Azure WebApp
        env:
          RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          APP_SERVICE_PLAN: ${{ secrets.AZURE_APP_PLAN_NAME }}
          DOCKER_USERNAME: <token>
          # This token will be replaced by temporary application token once support is added for GitHub Applications tokens for deploying to GPR
          DOCKER_PASSWORD: ${{ secrets.OCTODEMO_OCTODEMOBOT_GITHUB_REPO_AND_PACKAGES_TOKEN }}
          CONTAINER_REGISTRY_URL: ${{ steps.deployment_data.outputs.container_registry_url }}
          CONTAINER_IMAGE: ${{ steps.deployment_data.outputs.container_image }}
          APP_GITHUB_REF: ${{ steps.deployment_data.outputs.deployment_github_ref }}
          APP_TYPE: ${{ steps.deployment_data.outputs.app_type }}
          WEBAPP_NAME: ${{ steps.deployment_data.outputs.webapp_name }}
        run: |
          az webapp create --resource-group $RESOURCE_GROUP --plan $APP_SERVICE_PLAN --name $WEBAPP_NAME --deployment-container-image-name $CONTAINER_IMAGE
          az webapp config container set --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --docker-registry-server-password $DOCKER_PASSWORD --docker-registry-server-user $DOCKER_USERNAME --docker-registry-server-url $CONTAINER_REGISTRY_URL
          az webapp update -g $RESOURCE_GROUP -n $WEBAPP_NAME --set tags.ref=$APP_GITHUB_REF tags.type=$APP_TYPE

      - name: Deploy the WebApp Container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.deployment_data.outputs.webapp_name }}
          images: ${{ steps.deployment_data.outputs.container_image }}

      - name: Load Deployment
        timeout-minutes: 2
        continue-on-error: true
        run: curl https://${{ steps.deployment_data.outputs.webapp_name }}.azurewebsites.net

      - name: Report Success
        uses: octokit/request-action@v1.x
        with:
          route: POST /repos/:owner/:repo/deployments/:deployment_id/statuses
          deployment_id: ${{ github.event.deployment.id }}
          environment: ${{ github.event.deployment.environment }}
          description: "Deployed in ${{ github.event.deployment.environment }}"
          state: "success"
          environment_url: "https://${{ steps.deployment_data.outputs.webapp_name }}.azurewebsites.net"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Report Failure
        if: failure()
        uses: octokit/request-action@v1.x
        with:
          route: POST /repos/:owner/:repo/deployments/:deployment_id/statuses
          deployment_id: ${{ github.event.deployment.id }}
          description: "Deploy failed for ${{ github.event.deployment.environment }}"
          environment: ${{ github.event.deployment.environment }}
          state: "failure"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
